#!/usr/bin/env python

import json
import argparse
import sys
import requests
import polling
import urllib3
import logging
import smtplib
import os
import datetime
import calendar
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import COMMASPACE, formatdate
from email import encoders

try:
    import configparser as ConfigParser
except:
    import ConfigParser

def getSession(uri,port,l,p):
    global session
    url = "https://%s:%s%s" % (uri,port,"/session")
    payload = {'username': l, 'password': p}
    try:
      token = requests.post(url,json=payload,headers=headers,verify=False)
    except requests.exceptions.ConnectionError as e:
      logger.error("Connection Failed: %s", e)
      sys.exit(1)
    except requests.exceptions.Timeout as e:
      logger.error("Timeout Occurred while connecting: %s", e)
      sys.exit(1)
    except requests.exceptions.RequestException as e:
      logger.error("Error occurred trying to connect: %s", e)
      sys.exit(1)
    logger.debug('Session request result: %s', token.json())
    logger.info('Retrieved Session Token: %s', token.json()["token"])
    session.headers.update({'X-Cookie': 'token=' + (token.json())["token"]})

# Function for Policy Creation
def createPolicy(session,nesshost,nessport):
    # Set the URL for this REST call
    url = "https://%s:%s%s" % (nesshost, nessport, "/policies")
    data = open(args.policy).read()
    r = session.post(url, data=data, headers=headers, verify=False)
    logger.debug('createPolicy request result: %s', r.json())
    logger.debug('Retrieved Policy ID: %s', r.json()["policy_id"])
    return(r.json()["policy_id"])

def deletePolicy(session):
    url = "https://%s:%s%s%s" % (nesshost, nessport, "/policies/", policyid)
    r = session.delete(url, headers=headers, verify=False)
    logger.info('Deleted Policy %s', policyid)

def createScan(session):
    # Set the URL for this REST call
    url = "https://%s:%s%s" % (nesshost, nessport, "/scans")

    myscan = {}
    myscan['uuid'] = templateid

    settings = {'name': scan_name,
    'description': scan_desc,
    'enabled': scan_enabled,
    'launch': scan_launch,
    'policy_id': policyid,
    'text_targets': scan_targets
    }

    myscan['settings'] = settings

    scanjson = json.dumps(myscan)

    logger.debug('Scanner JSON is: %s', scanjson)

    r = session.post(url, data=scanjson, headers=headers, verify=False)
    logger.info('Created Scan ID: %s', r.json()['scan']['id'])
    return(r.json()['scan']['id'])

def deleteScan(session):
    url = "https://%s:%s%s%s" % (nesshost, nessport, "/scans/", scanid)
    r = session.delete(url, headers=headers, verify=False)
    logger.info('Deleted Scan ID: %s', scanid)

def launchScan(session):
    url = "https://%s:%s%s%s%s" % (nesshost, nessport, "/scans/", scanid, "/launch")
    logger.info('Launching Scan ID: %s', scanid)
    r = session.post(url, headers=headers, verify=False)
    logger.debug('Launched Scan ID %s: %s', scanid, r.json())

def getScanTemplateUUID(session,nesshost,nessport):
    url = "https://%s:%s%s" % (nesshost, nessport, "/editor/policy/templates")
    r = session.get(url, headers=headers, verify=False)
    #print(r.json()['templates'][0]['name'])
    for tc in r.json()['templates']:
        if tc['name'] == "custom":
            uuid = tc['uuid']
    return(uuid)

def scan_response(response):
    if response.json()['info']['status'] == "completed":
        logger.info('Scan has completed...')
        return True
    else:
        logger.info("Polling while waiting for scanner to finish...")
        logger.debug('Polling result was: %s', response.json()['info']['status'])
        return False

def report_response(response):
    if response.json()['status'] == "ready":
        logger.info('Report Generation has completed...')
        return True
    else:
        logger.info("Polling while waiting for report generation to finish...")
        logger.debug('Polling result was: %s', response.json()['status'])
        return False


def scanPolling(session):
    url = "https://%s:%s%s%s" % (nesshost, nessport, "/scans/", scanid)
    try:
        # Poll every 10 seconds for 82800 seconds (23 hours)
        polling.poll(lambda: session.get(url, headers=headers, verify=False), check_success=scan_response, step=10,
                     timeout=82800)
    except polling.TimeoutException:
        logger.info("Timeout waiting for Scan to complete...")
        print("Timed out waiting for Scan to complete. Check logs for additional information.")
        sys.exit(1)

def getReport(session):
    url = "https://%s:%s%s%s%s" % (nesshost, nessport, "/scans/", scanid, "/export")

    report = {}
    report['format'] = report_format
    report['chapters'] = report_types
    reportjson = json.dumps(report)

    r = session.post(url, data=reportjson, headers=headers, verify=False)
    logger.debug('Output from Report Generation: %s', r.json())
    filenum = r.json()['file']

    reporturl = "https://%s:%s%s%s%s%s%s" % (nesshost, nessport, "/scans/", scanid, "/export/", filenum, "/status")
    try:
        # Poll every 5 seconds for 300 seconds (5 minutes)
        polling.poll(lambda: session.get(reporturl, headers=headers, verify=False), check_success=report_response, step=5,
                     timeout=300)
    except polling.TimeoutException:
        logger.info("Timeout waiting for Report Generation to complete...")
        print("Timed out waiting for Report Generation to complete. Check logs for additional information.")
        sys.exit(1)

    pullreporturl = "https://%s:%s%s%s%s%s%s" % (nesshost, nessport, "/scans/", scanid, "/export/", filenum, "/download")
    r = session.get(pullreporturl, headers=headers, verify=False, stream=True)
    with open(report_filename, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024):
            if chunk:
                f.write(chunk)
    logger.info('Report downloaded to %s', report_filename)

def send_mail(send_from, send_to, subject, text, filetosend, server, port):
    msg = MIMEMultipart()
    msg['From'] = send_from
    msg['To'] = send_to
    msg['Date'] = formatdate(localtime=True)
    msg['Subject'] = subject

    msg.attach(MIMEText(text))

    part = MIMEBase('application', "octet-stream")
    part.set_payload(open(filetosend, "rb").read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', 'attachment; filename="{0}"'.format(os.path.basename(filetosend)))
    msg.attach(part)

    smtp = smtplib.SMTP(server, port)
    try:
        smtp.sendmail(send_from, send_to, msg.as_string())
    except smtplib.SMTPException as e:
        logger.info("Error while attempting to Email Report...")
        logger.info("Error was : %s", str(e))
        sys.exit(1)
    smtp.quit()

def check_schedule():
    if args.scheduler:
        today = datetime.datetime.now()
	logger.debug("Current date is: %s", today)
        
        if schedule_lastofmonth != "NULL":
	    logger.debug("LastOfMonth was: %s -- %s", schedule_lastofmonth, schedule_lastofmonth.upper())
            if schedule_lastofmonth.upper() == "SUNDAY":
                numday = 1
            elif schedule_lastofmonth.upper() == "SATURDAY":
                numday = 2
            elif schedule_lastofmonth.upper() == "FRIDAY":
                numday = 3
            elif schedule_lastofmonth.upper() == "THURSDAY":
                numday = 4
            elif schedule_lastofmonth.upper() == "WEDNESDAY":
                numday = 5
            elif schedule_lastofmonth.upper() == "TUESDAY":
                numday = 6
            elif schedule_lastofmonth.upper() == "MONDAY":
                numday = 7
            runday = max(week[-numday] for week in calendar.monthcalendar(today.year,today.month))
	    logger.debug("Run Day was: %s, Month was: %s, Year was: %s", runday, today.month, today.year)
            if runday == today.day and schedule_hour == today.strftime("%H") and schedule_minute == today.strftime("%M"):
                return 0
            else:
		logger.debug("Not Running -- RunDay: %s, LastOfMonth: %s, Year: %s, Month: %s, Day: %s, Hour: %s, Minute: %s", runday, schedule_lastofmonth, today.year, today.month, today.day, today.hour, today.minute)
                raise ValueError()
        else:
            if (schedule_day == today.strftime("%D") or schedule_day == "*") and (schedule_hour == today.strftime("%H") or schedule_hour == "*") and (schedule_minute == today.strftime("%M") or schedule_minute == "*"):
                return 0
            else:
                logger.debug("Not running: day %s, hour %s, minute %s -- config: day %s, hour %s, minute %s", today.strftime("%d"), today.strftime("%H"), today.strftime("%M"), schedule_day, schedule_hour, schedule_minute)
		raise ValueError()
    else:
        sys.exit(1)



# Arguments for script
parser = argparse.ArgumentParser()
parser.add_argument("-c", "--config", default='example.cfg', help="Config File to Use")
parser.add_argument("-t", "--targets",default='',help="Targets for the Scan")
parser.add_argument("-p", "--policy",default='Example_Policy.json',help="Scanning Policy File to Use")
parser.add_argument("-d", "--debug", action='store_true', help="Enable Debug Logging")
parser.add_argument("-s", "--scheduler", action='store_true', help="Enable Internal Scheduler Check")

args = parser.parse_args()

# Disable Certificate warnings
urllib3.disable_warnings()

#if not args.config:
#    print("No config file specified, please specify with -c")
#    sys.exit(1)

# Read in Config File
config = ConfigParser.ConfigParser()
config.readfp(open(args.config))

try:
    login = config.get('server', 'login')
    password = config.get('server', 'password')
    nesshost = config.get('server', 'uri')
    nessport = config.get('server', 'port')
    scan_name = config.get('scan', 'name')
    scan_desc = config.get('scan', 'description')
    scan_enabled = config.get('scan', 'enabled')
    scan_launch = config.get('scan', 'launch')
    if not args.targets:
        scan_targets = config.get('scan', 'targets')
    else:
        scan_targets = args.targets
    report_format = config.get('report', 'format')
    report_types = config.get('report', 'types')
    report_filename = config.get('report', 'filename')
    email_from = config.get('email', 'from')
    email_to = config.get('email', 'to')
    email_subject = config.get('email', 'subject')
    email_server = config.get('email', 'server')
    email_port = config.get('email', 'port')
    log_path = config.get('logging', 'path')
    schedule_minute = config.get('schedule','minute')
    schedule_hour = config.get('schedule','hour')
    schedule_day = config.get('schedule','day')
    schedule_lastofmonth = config.get('schedule','lastofmonth')
except:
    pass

#Implement Logging
# https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
logger = logging.getLogger(__name__)
if args.debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)
handler = logging.FileHandler(log_path)
if args.debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
# End Logging Setup

#Implement scheduler check in config
# CODE HERE
if args.scheduler:
  try:
    check_schedule()
  except ValueError:
    # Exit since we are not scheduled to run    
    sys.exit(0)

# Global Variables
headers = {'Content-Type': 'application/json'}
session = requests.Session()

# The Main Show starts here
logger.info('-----START-----')
logger.info('Scanner Start')
getSession(nesshost,nessport,login,password)

# Create the Nessus Policy
policyid = createPolicy(session,nesshost,nessport)

# Create the Nessus Scan
templateid = getScanTemplateUUID(session,nesshost,nessport)
scanid = createScan(session)

#Launch the Scan
launchScan(session)

#Wait for the scan to finish
scanPolling(session)

#Generate and Download Report
getReport(session)

#Email Report
send_mail(email_from, email_to, email_subject, '', report_filename, email_server, email_port)

#Cleanup
deleteScan(session)
deletePolicy(session)

logger.info('Scanner Work is Completed')
logger.info('-----END-----')
